spring.application.name=globetrotter

spring.datasource.url=jdbc:postgresql://localhost:5432/globetrotter
spring.datasource.username=postgres
spring.datasource.password=Param@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true